version: 0.2

env:
  variables:
    AWS_REGION: sa-east-1
    IMAGE_REPO_NAME: devcloud-ecr
    CLUSTER_NAME: devcloud-ecs
    SERVICE_NAME: devcloud-service
    TASK_DEFINITION: devcloud-task

phases:
  pre_build:
    commands:
      - echo 🔐 Fazendo login no Amazon ECR...
      - $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 136508419156.dkr.ecr.$AWS_REGION.amazonaws.com)
      - export REPOSITORY_URI=136508419156.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - echo 📦 URI do repositório: $REPOSITORY_URI
      - echo Definindo variáveis de ambiente para a Task Definition...

  build:
    commands:
      - echo 🚀 Build da imagem Docker...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo 📤 Enviando imagem para o ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - echo 📋 Atualizando a Task Definition do ECS...
      - ecs_task_definition=$(aws ecs register-task-definition \
          --family $TASK_DEFINITION \
          --container-definitions "[{\"name\":\"devcloud-container\",\"image\":\"$REPOSITORY_URI:latest\",\"memory\":512,\"cpu\":256,\"essential\":true,\"portMappings\":[{\"containerPort\":80,\"hostPort\":80}]}]" \
          --query 'taskDefinition.taskDefinitionArn' --output text)
      - echo Tarefa registrada: $ecs_task_definition
      - echo 🎯 Atualizando o serviço ECS...
      - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --task-definition $ecs_task_definition
